### ISSUE TITLE
Pa_GetDefaultInputDevice returns paNoDevice on error

### ISSUE THREAD

**Issue by joerg-krause** [mvdnes/portaudio-rs#10]
The portaudio API says [Pa_GetDefaultInputDevice] (http://portaudio.com/docs/v19-doxydocs/portaudio_8h.html#abf9f2f82da95553d5adb929af670f74b) returns `paNoDevice` if no default input device is available or an error was encountered. The type of `paNoDevice` is defined as `PaDeviceIndex` not `PaError`.

The same goes for Pa_GetDefaultOutputDevice.

Running portaudio with API logging:

```sh
Pa_GetDefaultInputDevice returned:
	PaDeviceIndex: -1
Pa_GetDefaultOutputDevice returned:
	PaDeviceIndex: 6
```

**Comment by mvdnes** [comment]
Thanks for the report! :+1:
