### ISSUE TITLE
Possible memory corruption on stream drop

### ISSUE THREAD

**Issue by herrernst** [mvdnes/portaudio-rs#11]
I've seen occasional crashes using portaudio-rs when a stream gets freed. I've [uploaded an example here](https://github.com/herrernst/rust-portaudio-example), which sometimes (not always) crashes on Linux x64 with `Segmentation fault (core dumped)`.
When running with rust-gdb I get:
```
Program received signal SIGSEGV, Segmentation fault.
0x0000555555558655 in for$LT$$u27$r$C$$u20$$u27$r$GT$$u20$core..ops..FnMut$LP$$RF$$u27$r$u20$$u5b$f32$u5d$$C$$u20$$RF$$u27$r$u20$mut$u20$$u5b$f32$u5d$$C$$u20$portaudio..stream..StreamTimeInfo$C$$u20$portaudio..stream..StreamCallbackFlags$RP$$u20$.$GT$$u20$portaudio..stream..StreamCallbackResult$u20$$u2b$$u20$$u27$static::drop.4853::h04e8fe4f55ebecbf () at src/main.rs:39
```
On an Raspberry Pi (armhf), I get ```*** Error in `target/debug/main': corrupted double-linked list: 0x55afb230 ***```.
Note that the example uses the system memory allocator, because I couldn't produce a testcase when using jemalloc (but I have also seen crashes when using jemalloc in an larger project).
For my fix, see #12.

**Comment by herrernst** [comment]
Thank you!

**Comment by mvdnes** [comment]
Thanks for the analysis and fix! :+1: I have not tested it thoroughly, but I think you've got the right idea! Added a bit of additional cleanup afterwards. If you run into issues again, do not hesitate to post an issue.

**Comment by herrernst** [comment]
Thanks for your quick merge, works with your cleanup! :+1:
