### ISSUE TITLE
publish package on crates-io

### ISSUE THREAD

**Issue by bburdette** [mvdnes/portaudio-rs#16]
It would be nice if there was a package on crates-io.  Would be nice to pin my project to a specific version of portaudio-rs.

**Comment by mvdnes** [comment]
I was not planning on actively supporting this library. Maybe you can try any of the [other] libraries?

[other]: https://crates.io/search?q=portaudio

**Comment by bburdette** [comment]
Sure, I understand not wanting to be a lib maintainer.  Before trying this lib out I tried cpal, rust-portaudio, alsa, and rsoundio, but none of them were able to be both low latency for IO and run on ARM.  Its been a year or so since I tried all of those, but maybe one of them is in better shape now.  For me this was the best option at the time!

**Comment by mvdnes** [comment]
I decided to publish the crate! I had to do a small rename though: [portaudio-rs].

[portaudio-rs]: https://crates.io/crates/portaudio-rs

**Comment by bburdette** [comment]
good to hear!
