### ISSUE TITLE
PaError should implement Error

### ISSUE THREAD

**Issue by BartMassey** [mvdnes/portaudio-rs#19]
It would be really convenient if `PaError` would implement `std::error::Error`, as this would allow use with `?`. The diff is below: I can make a pull request if desired.

```
diff --git a/src/pa.rs b/src/pa.rs
index 32dda18..bc89e9e 100644
--- a/src/pa.rs
+++ b/src/pa.rs
@@ -142,6 +142,8 @@ impl fmt::Debug for PaError
     }
 }
 
+impl std::error::Error for PaError {}
+
 /// A result type wrapping PaError.
 ///
 /// The original NoError is mapped to Ok(()) and other values mapped to Err(x)
```

Thanks much for `portaudio-rs`: unlike `rust-portaudio`, and unlike `cpal`, this one seems to work reliably and easily at least for my use case.

**Comment by mvdnes** [comment]
Good to hear this library still works.
Although I do not actively maintain this, I am happy to do small edits like this.
I have applied your suggested fix.
Thanks :+1:

**Comment by BartMassey** [comment]
Thanks very much! Seems to work fantastic so far: really happy to be using it.

**Comment by BartMassey** [comment]
Also, thanks much for immediately pushing to `crates.io`. Greatly appreciated.
