### ISSUE TITLE
Co-maintainer?

### ISSUE THREAD

**Issue by BartMassey** [mvdnes/portaudio-rs#26]
Been thinking about this fantastic project a lot, because my students and I are using it pretty heavily right now. Any interest in having a co-maintainer? I'd be happy to run the queue and pay attention, and would be happy to defer to you on all decisions. I have quite a bit of open source and Rust experience, and am pretty sure I would be a net positive.

If not, that's cool, of course. Thanks for a great crate!

(Sorry to post this here publicly, but don't have any other obvious means of contact.)

**Comment by mvdnes** [comment]
It is nice someone is using this code, as I have lost most of my interest in it quite some time ago.
As you seem to have some good ideas I will add you as a co-maintainer! Welcome.

**Comment by BartMassey** [comment]
Thanks much!
