### ISSUE TITLE
Having to change u64 to u32 in places to get it to work

### ISSUE THREAD

**Issue by Paul-Andre** [mvdnes/portaudio-rs#3]
I got the example working, but only after modifying the "stream.rs" source file by replacing a bunch of "u64"s by "u32" after the compiler gave me a bunch of errors about mismatched types concerning the sample type flags and frames per buffer.

I have a 32 bit linux machine. Is it possible that your code assumes a 64 bit machine in some places?

**Comment by mvdnes** [comment]
Thanks for reporting the issue!
A `c_ulong` is not the same on 32 and 64 bit. It should now work again.

**Comment by Paul-Andre** [comment]
Thanks, it does work now.
