### ISSUE TITLE
No input device available

### ISSUE THREAD

**Issue by joerg-krause** [mvdnes/portaudio-rs#9]
Sorry for my ignorance, but how do I open a stream if no input device is available?

The portaudio API says:

> inputParameters must be NULL for output-only streams.

I don't know much about Rust, yet. So, can you please provide an example for an output-only stream? Many thanks!

**Comment by mvdnes** [comment]
That is something I have not thought of when designing the library. Something like that would be possible by changing the parameter to an `Option<StreamParameters<I>>` and converting that to a null pointer when necessary.

For the time being, you could also use the `open_default` function with `num_input_channels` of 0.

**Comment by joerg-krause** [comment]
Having the possibility to set a null pointer would be great!

The default device returned by portaudio is the raw alsa hardware device (without an input), but I want to use a software volume control.

**Comment by mvdnes** [comment]
Updated in 3af3b338.

See https://mvdnes.github.io/rust-docs/portaudio-rs/portaudio/stream/struct.Stream.html#method.open

You may need to add some type inference using `Stream::<i8, _>::open(...)`

**Comment by joerg-krause** [comment]
Many thanks for the update!

Nitpick: If no input device is available for the test demo the function will return at this point https://github.com/mvdnes/portaudio-rs/blob/master/examples/test.rs#L138.

**Comment by mvdnes** [comment]
Thanks for the info, I have also fixed `is_format_supported` to allow that to accept a `None` as well.
